name: Build and Deploy Laravel Filament
on:
  push:
    branches:
      - main
      - add-finance-module
  workflow_dispatch:
jobs:
  laravel-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸšš Checkout Code
        uses: actions/checkout@v4

      - name: ğŸ˜ Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: ğŸ“¦ Install Composer Dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: ğŸŸ¢ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Rekomendasi untuk Tailwind v4 / Filament v4

      - name: ğŸ“¦ Install NPM & Build Assets
        run: |
          npm install
          npm run build # Ini akan memproses Vite & Filament Custom Theme

      - name: ğŸ“‚ Sync Files to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_TARGET_DIR }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/tests/**
            .env.example
            phpunit.xml
            README.md
